// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: CreateProfile.sql

package db

import (
	"context"
)

const createProfile = `-- name: CreateProfile :one
insert into profiles (user_id)
values ($1)
returning profile_id
`

// Creates a new profile entry for the specified user and returns the new profile_id.
func (q *Queries) CreateProfile(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, createProfile, userID)
	var profile_id int32
	err := row.Scan(&profile_id)
	return profile_id, err
}
