// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: CreateProfileFile.sql

package db

import (
	"context"
)

const createProfileFile = `-- name: CreateProfileFile :exec
insert into profile_files (profile_id, profile_name, profile_content, profile_description)
values ($1, $2, $3, $4)
`

type CreateProfileFileParams struct {
	ProfileID          int32
	ProfileName        string
	ProfileContent     []byte
	ProfileDescription string
}

// Creates an associated profile file for the specified profile.
func (q *Queries) CreateProfileFile(ctx context.Context, arg CreateProfileFileParams) error {
	_, err := q.db.Exec(ctx, createProfileFile,
		arg.ProfileID,
		arg.ProfileName,
		arg.ProfileContent,
		arg.ProfileDescription,
	)
	return err
}
