// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: CreateUser.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
insert into users (user_name, user_role, user_password_hash, user_email) values ($1, $2, $3, $4)
returning user_id
`

type CreateUserParams struct {
	UserName         string
	UserRole         string
	UserPasswordHash []byte
	UserEmail        string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserName,
		arg.UserRole,
		arg.UserPasswordHash,
		arg.UserEmail,
	)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}
