// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: DeleteUser.sql

package db

import (
	"context"
)

const deleteUser = `-- name: DeleteUser :exec
delete from users
where user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}
