// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: GetUserByID.sql

package db

import (
	"context"
)

const getUserByID = `-- name: GetUserByID :one
select user_id, user_name, user_role, user_password_hash, user_email
from users
where user_id = $1
`

type GetUserByIDRow struct {
	UserID           int32
	UserName         string
	UserRole         string
	UserPasswordHash []byte
	UserEmail        string
}

func (q *Queries) GetUserByID(ctx context.Context, userID int32) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.UserRole,
		&i.UserPasswordHash,
		&i.UserEmail,
	)
	return i, err
}
