// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Profile struct {
	ProfileID        int32
	UserID           int32
	ProfileCreatedAt time.Time
	ProfileUpdatedAt time.Time
}

type ProfileFile struct {
	ProfileID          int32
	ProfileFileName    string
	ProfileFileContent []byte
}

type User struct {
	UserID                int32
	UserName              string
	UserRole              string
	UserPasswordHash      []byte
	UserPasswordChangedAt time.Time
	UserEmail             string
	UserCreatedAt         time.Time
	UserUpdatedAt         time.Time
}
