// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Profile struct {
	ProfileID        int32
	UserID           int32
	ProfileCreatedAt pgtype.Timestamp
	ProfileUpdatedAt pgtype.Timestamp
}

type ProfileFile struct {
	ProfileID          int32
	ProfileName        string
	ProfileDescription string
	ProfileContent     []byte
}

type User struct {
	UserID                int32
	UserName              string
	UserRole              string
	UserPasswordHash      []byte
	UserPasswordChangedAt pgtype.Timestamp
	UserEmail             string
	UserCreatedAt         pgtype.Timestamp
	UserUpdatedAt         pgtype.Timestamp
}
