// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: UpdateUserName.sql

package db

import (
	"context"
)

const updateUserName = `-- name: UpdateUserName :exec
update users
set user_name = $1,
    user_updated_at = now()
where user_id = $2
`

type UpdateUserNameParams struct {
	UserName string
	UserID   int32
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, updateUserName, arg.UserName, arg.UserID)
	return err
}
