// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: UpdateUserPasswordHash.sql

package db

import (
	"context"
)

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
update users
set user_password_hash = $1,
    user_password_changed_at = now(),
    user_updated_at = now()
where user_id = $2
`

type UpdateUserPasswordHashParams struct {
	UserPasswordHash []byte
	UserID           int32
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPasswordHash, arg.UserPasswordHash, arg.UserID)
	return err
}
