// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: UpdateUserEmail.sql

package db

import (
	"context"
)

const updateUserEmail = `-- name: UpdateUserEmail :exec
update users
set user_email = $1,
    user_updated_at = now()
where user_id = $2
`

type UpdateUserEmailParams struct {
	UserEmail string
	UserID    int32
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateUserEmail, arg.UserEmail, arg.UserID)
	return err
}
