// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: proto/csol.proto
//
// This is a STUB — regenerate with:
//   protoc --go_out=internal/rpc/proto --go_opt=paths=source_relative \
//          --go-grpc_out=internal/rpc/proto --go-grpc_opt=paths=source_relative \
//          proto/csol.proto

package proto

import (
	"context"

	"google.golang.org/grpc"
)

// ── Client-side interface ────────────────────────────────────────────────────

type ControlServiceClient interface {
	SendState(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ControllerState, Ack], error)
	ExecuteCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Ack, error)
}

// ── Server-side interface ────────────────────────────────────────────────────

type ControlServiceServer interface {
	SendState(grpc.ClientStreamingServer[ControllerState, Ack]) error
	ExecuteCommand(context.Context, *Command) (*Ack, error)
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer should be embedded to have forward
// compatible implementations.
type UnimplementedControlServiceServer struct{}

func (UnimplementedControlServiceServer) SendState(grpc.ClientStreamingServer[ControllerState, Ack]) error {
	return nil
}

func (UnimplementedControlServiceServer) ExecuteCommand(context.Context, *Command) (*Ack, error) {
	return nil, nil
}

func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}

// ── Registration helper ─────────────────────────────────────────────────────

var _ControlService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "csol.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommand",
			Handler: func(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
				in := new(Command)
				if err := dec(in); err != nil {
					return nil, err
				}
				if interceptor == nil {
					return srv.(ControlServiceServer).ExecuteCommand(ctx, in)
				}
				info := &grpc.UnaryServerInfo{
					Server:     srv,
					FullMethod: "/csol.ControlService/ExecuteCommand",
				}
				handler := func(ctx context.Context, req any) (any, error) {
					return srv.(ControlServiceServer).ExecuteCommand(ctx, req.(*Command))
				}
				return interceptor(ctx, in, info, handler)
			},
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendState",
			ClientStreams: true,
		},
	},
	Metadata: "proto/csol.proto",
}

// RegisterControlServiceServer registers the ControlServiceServer with the
// gRPC server.
func RegisterControlServiceServer(s *grpc.Server, srv ControlServiceServer) {
	s.RegisterService(&_ControlService_serviceDesc, srv)
}
