// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/csol.proto
//
// This is a STUB — regenerate with:
//   protoc --go_out=internal/rpc/proto --go_opt=paths=source_relative \
//          --go-grpc_out=internal/rpc/proto --go-grpc_opt=paths=source_relative \
//          proto/csol.proto

package proto

type ControllerState struct {
	ControllerId string `protobuf:"bytes,1,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
	StateJson    string `protobuf:"bytes,2,opt,name=state_json,json=stateJson,proto3" json:"state_json,omitempty"`
	TimestampMs  int64  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
}

type Command struct {
	CommandId string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Action    string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Payload   string `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

type Ack struct {
	Ok      bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}
