-- This file is automatically generated. Do not change!
PATH = [[{}]] -- Executor search path

---Include a module.
---@param file_name string module name with .lua suffix (e.g. "core/Runtime.lua", "custom/Setting.lua")
function Include(file_name)
    dofile(PATH:format(file_name))
end

Include("core/Main.lua")

Main()

