# 架构设计

集成工具支持单机和联机模式。
使用单机模式时，本地引擎启动后，会在本地启动控制器和执行器两个组件，控制器实时地向执行器传递命令，在游戏内完成自动化操作。
联机模式在单机模式的基础上增加了远程控制服务支持。

在使用单机模式时，本地引擎（Local Engine）运行于 Windows PC，负责启动和管理控制器和执行器两个组件。
若启用联机模式，则控制器在启动时需要提供用户账户及密码。本地引擎连接到调度服务器后，实时将当前状态及日志通过 gRPC stream 同步到调度服务器。调度服务器也可实时将来自操纵器的命令通过 gRPC 转发给本地引擎，本地引擎再将命令转发给控制器和执行器。
用户通过操纵器连接到调度服务器后，可以远程操纵控制器和执行器，获取当前状态和日志信息，并实时操纵本地引擎的运行状态（如启动、切换模式、停止等）。

## 本地引擎

### 控制器

控制器（Controller）运行于 Windows PC，控制器通过 Windows API 实时截取游戏画面，使用 OpenCV 进行预处理后交由 ONNX 部署的多种深度学习模型进行游戏内状态判定，状态更新后实时向 Lua 实现的执行器下达命令，在游戏内完成自动化操作。

### 执行器

执行器（Executor）封装了 Logitech G HUB 的 Lua API，运行于 Windows PC，接收控制器下达的命令并通过 Logitech G HUB 的 Lua API 模拟键盘和鼠标输入，实现对游戏的自动化操作。

## 操纵器

操纵器（Manipulator）是由 RevealJS 实现的 Web 应用，可实现对控制器、执行器的远程操纵。

## 调度器

调度器（Scheduler）是由 Go 实现的后端服务，负责处理用户登录和权限验证，登陆后处理来自操纵器的命令，并将其转发给控制器和执行器。控制器的状态实时同步到调度器，操纵器可以通过调度器获取控制器的状态信息。

```plain
                 ┌──────────────────────────────┐
                 │         Manipulator          │
                 │     HTTPS + WebSocket        │
                 └──────────────┬───────────────┘
                                │
                 ┌──────────────────────────────┐
                 │          Scheduler           │
                 │  - Auth (HTTPS)              │
                 │  - gRPC Service              │
                 │  - WebSocket Hub             │
                 │  - Redis                     |
                 │  - PostgreSQL                |
                 │  - Kafka                     |
                 └──────────────┬───────────────┘
                                │
                 ┌──────────────────────────────┐
                 │            Engine            │
                 │  - gRPC client (control)     │
                 │  - WebSocket client (real)   │
                 └──────────────────────────────┘
```